ClickHouse/dbt-clickhouse

- README.md
- dbt/adapters/clickhouse/connections.py
- dev_requirements.txt
- setup.py
Allows users to specify clickhouse-driver Client options:
- `secure` if their ClickHouse instance is behind a secure port
- `verify` if ssl verify should be performed.
_(both defaulted to False)_
> Adds verify + secure boolean to ClickhouseCredentials

- dbt/include/clickhouse/macros/adapters.sql
**Summary:**
This PR adds the support for `Join` engine, useful for joining large tables that couldn't be done using a `MergeTree()`.
---
**Discussion:**
In my opinion, we should add a way to disable the default `order by (tuple())` to avoid adding manually a support for each engine that does not support this instruction.
I have two proposals for this:
- ~~Removing the default value (`tuple()`), but this could break some existing code (?)~~ Breaking, the empty tuple is required for `MergeTree` ([see here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-query-clauses))
- Adding a support for `None` value, something such as:
```
{{ config(
engine='Join(ANY, LEFT, id)',
order_by=None
) }}
```
If anyone has any better idea for implementing this, I'm …
> Add support for Join engine

- dbt/adapters/clickhouse/column.py
Fixing the bug, now the regex will catch the last bracket inside Nullable.
Closes issue #40
> Fix brackets regex

- README.md
- dbt/include/clickhouse/macros/materializations/incremental.sql
- tests/integration/adapter/test_basic.py
1. Changed temporary table to regular MergeTree tabel to avoid memory limitations.
2. Added an option to run inserts only (inserts_only=True). In this case, there will be no intermediate table, all incremental changes are added to the target table. This is essentially the same as running an update on incremental table without unique_key.
> Improved Incremental materialization:

- CHANGELOG.md
- README.md
- Refactor personal links from the old repo
- Move a block about author in README to the down of the page, because this is not critical information for use
> Fix old repo links

- dbt/adapters/clickhouse/connections.py
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/seed.sql
- dev_requirements.txt
- setup.py
Reverting to correctly nulls as defaults without Nullable columns by falling back to ClickHouse CSV insert handling.
> Revert to CSV insert

- dbt/include/clickhouse/macros/catalog.sql
Cause we use syntax 22.1 we can use comment of columns / tables now.
> Fix columns / tables comment

- dbt/adapters/clickhouse/impl.py
I removed the single db limitation from get_catalog.
Reason: when using different quoting policies in a dbt project, they are stored as separate schema info. The previous check we did disallowed multiple schema info, and I don't see a good reason not to allow multiple information schema in this case.
@silentsokolov, @genzgd  please let me know if I'm missing something here.
> Removed single database limitation in get_catalog

- .gitignore
- dbt/include/clickhouse/macros/adapters.sql
- dbt/include/clickhouse/macros/materializations/incremental.sql
- dbt/include/clickhouse/macros/materializations/snapshot.sql
- dbt/include/clickhouse/macros/materializations/table.sql
- dbt/include/clickhouse/macros/materializations/view.sql
When working with complex DBT projects, sometimes Cron jobs and builds interfere with each other, and cause SELECT errors or deadlocks when tables are being recreated by one or several processes. This PR, in combination with Atomic engine and [SYNC clickhouse setting](https://clickhouse.com/docs/en/operations/settings/settings/#database_atomic_wait_for_drop_and_detach_synchronously) should help avoid those issues.
For now table & view materializations are copied from dbt-core@v1.1.2 and modified
https://github.com/dbt-labs/dbt-core/tree/v1.1.2
When the 1.2.x support update is released I can update them accordingly
> Adaptive materialization strategy when using Atomic schema engine

- .github/workflows/lint.yml
- .github/workflows/pypi.yml
- .github/workflows/test_matrix.yml
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/dbclient.py
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/test_incremental.py
- tests/integration/docker-compose.yml
Fix info message when RENAME TABLE not available, fix edge case for CREATE TABLE AS ... EMPTY which is not available in some pre-stable 22.7.1 ClickHouse version.
> Release 1.3.1

- dbt/include/clickhouse/macros/adapters/apply_grants.sql
Currently if the grant is given to a role, the `user_name` is null which leads to the below error when running `apply_grants`
```
'NoneType' object has no attribute 'casefold'
```
> In apply grants use role_name when user_name not available

- dbt/include/clickhouse/macros/adapters.sql
- dbt/include/clickhouse/macros/adapters/apply_grants.sql
Added cluster clause for DDLs, I believe this fixes #117 and also #95  as long as your engine uses the `{uuid}` macro for path.
see https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper-uuid/#alternatives
> Update `on cluster` clause

- dbt/include/clickhouse/macros/adapters.sql
Sync tables across replicas before exchange to preserve consistency. This was recommended to us by Altinity, we used it on our cluster without any degradation in performance.
> Sync replica before exchange on `exchange_tables_atomic`

- dbt/include/clickhouse/macros/catalog.sql
- dbt/include/clickhouse/macros/persist_docs.sql
- tests/integration/adapter/persist_docs/fixtures.py
- tests/integration/adapter/persist_docs/test_persist_docs.py
Call MODIFY COMMENT only if we really have description for column
Squash all alters for comments into single command to reduce number of SQL calls
Given this model
```yml
- name: table
description: Parsed events
columns:
- name: date
description: Date when error occurred
- name: timestamp
description: timestamp from Kafka metadata
- name: app_id
- name: user_id
- name: platform_id
```
Previous behaviour
```sql
alter table db.table modify comment 'Parsed events'
alter table db.table comment column date 'Date when error occurred'
alter table db.table comment column timestamp 'timestamp from Kafka metadata'
alter table db.table comment column platform_id ''
alter table db.table comment column app_id ''
alter table db.table comment column user_id ''
```
New behaviour
```sql
alter table …
```
> Reduce number of MODIFY COMMENT queries count

- dbt/adapters/clickhouse/dbclient.py
When running an on-premise ClickHouse cluster, dbt-clickhouse will attempt to create the database but doesn't yet take cluster mode into account. With this PR, I attempted to solve this issue by taking into account by checking if a cluster name is set in the credentials. If it is present, it adds it to the create database clause respecting the syntax from https://clickhouse.com/docs/en/sql-reference/statements/create/database.
I've tested it, but as the whole dbt-clickhouse repo doesn't have tests for cluster mode, I've not added integration tests here.
> Fix database creation when cluster name is defined

- dbt/adapters/clickhouse/credentials.py
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/distributed_table.sql
Add distributed table materialization and local/shard/node suffix config
> Distributed table materialization

- dbt/include/clickhouse/macros/adapters.sql
- dbt/include/clickhouse/macros/materializations/table.sql
This changes the SYSTEM SYNC REPLICA query to have a space between the ON CLUSTER clause and the table name.
Solves #167
> Add space to exchange_tables_atomic macro

- .github/workflows/test_cloud.yml
- .github/workflows/test_matrix.yml
- CHANGELOG.md
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/connections.py
- dbt/adapters/clickhouse/dbclient.py
Fix bad log statements in exchange_tables test, fix invalid exception constructor for non-standard ClickHouse exceptions.
> Fix bad logging/error handling

- .github/workflows/pypi.yml
- .github/workflows/test_cloud.yml
- CHANGELOG.md
- README.md
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/dbclient.py
- tests/integration/adapter/persist_docs/test_persist_docs.py
- tests/integration/adapter/test_comments.py
Fixes lightweight deletes by actively setting `allow_nondeterministic_mutations` at the query level instead of relying on SET statements.
> Lw delete set fix

- dbt/adapters/clickhouse/dbclient.py
- tests/integration/adapter/test_errors.py
Add a simple error test, minor syntax fix for merge compatibility
> Add basic error test, fix minor merge conflict

- dbt/include/clickhouse/macros/materializations/table.sql
Due to a change in PR Release 1 5 0  the multiline code was consolidated into a single line. This cause an issue if we use it with SQLFluff and use the --noqa keyword or add any comment to the last line resulting a commented-out closing parenthesis. 
Code example:
Before the  original change code got compile like this : 
``` 
create table x.y
engine = ReplicatedMergeTree
order by (token_address,address)
empty
as (
SELECT
x,
y,
z
FROM source
settings optimize_aggregation_in_order=1 --noqa
)
``` 
After the release code gets compile into the format below and resulting syntax error:
``` 
create table x.y
engine = ReplicatedMergeTree
order by (token_address,address)
empty
as (
SELECT
x,
y,
z
FROM source
settings optimize_aggregation_in_order=1 --noqa )
```
> Adjust the wrapper parenthesis around the table materialization sql code

- dbt/include/clickhouse/macros/materializations/incremental/incremental.sql
Table creation fails in the situation where:
- you are **not** using distributed materializations
- you are using `ReplicatedMergeTree` table engines
- you are using `cluster_mode: true`
- you have defined a `unique_key` for a model
- you are using legacy incremental model strategy
The cause is twofold:
1. `create table [table1] as [table2] on cluster [cluster]` is invalid SQL for ClickHouse (at least for OSS). The `on cluster [cluster]` clause is not supported for `create table .. as` statements.
2. When removing the `on_cluster_clause`, table creation fails on `Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Macro 'uuid' and empty arguments of ReplicatedMergeTree are supported only for ON CLUSTER queries with Atomic database engine. (BAD_ARGUMENTS)`.
So in this …
> Fix creation of replicated tables when using legacy strategy and unique_key

- CHANGELOG.md
- README.md
- dbt/adapters/clickhouse/credentials.py
- dbt/adapters/clickhouse/dbclient.py
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/incremental/incremental.sql
- dbt/include/clickhouse/macros/materializations/seed.sql
- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/basic/test_basic.py
- tests/integration/adapter/clickhouse/test_clickhouse_table_materializations.py
- tests/integration/adapter/constraints/test_constraints.py
- tests/integration/adapter/incremental/test_base_incremental.py
Clean up model settings handling to fix some bugs.
> Bug fixes related to model settings.

- dbt/include/clickhouse/macros/materializations/materialized_view.sql
- tests/integration/adapter/test_materialized_view.py
Change: Adds a materialization macro to create and update materialized views.
Unlike #123, this is a separate materialization than tables and views and will create both the target table and the materialized view from one query. The model name is used for the target table and the materialized view appends `_mv` to the model name.
Since this reuses functionality from the table materialization, the configuration properties (`order_by`, `primary_key`, etc.) should work as expected. Similarly, the cluster clause seems to be added when appropriate.
> Add materialization macro for materialized view

- CHANGELOG.md
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/errors.py
- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/util.py
- dbt/include/clickhouse/macros/materializations/incremental/incremental.sql
- tests/integration/adapter/basic/test_incremental.py
- tests/integration/adapter/incremental/test_schema_change.py
Fix (with limited support) `on_schema_change` feature.
> Release 1 6 2

- CHANGELOG.md
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/impl.py
- dev_requirements.txt
- setup.py
> Release 1 7 0

- dbt/adapters/clickhouse/httpclient.py
- dbt/adapters/clickhouse/nativeclient.py
Appending `LIMIT 0` to queries that already have a LIMIT results in a syntax error:
```
... limit 10000 LIMIT 0 FORMAT JSON ...
>>> Code: 62. DB::Exception: Syntax error: failed at position 6358 ('LIMIT') (line 200, col 17): LIMIT 0
FORMAT JSON.
```
This is resolved by wrapping the query inside a select statement and limiting this clause.
> Wrap columns_in_query query in select statement

- dbt/include/clickhouse/macros/materializations/materialized_view.sql
- tests/integration/adapter/materialized_view/test_materialized_view.py
The existing implementation of materialized views had one case where the target relation name was passed as a string of just the table name, instead of the full relation object. This meant that any custom schema would not be included in the final DDL statement, and the MV would break as it would try to write to a target table that didn't exist. This change passes the full relation object when getting the "create materialized view" SQL, which in turn provides the full path to the table in every case.
> fix: use correct schema for MV target tables

- CHANGELOG.md
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/schema_tests/relationships.sql
- dbt/include/clickhouse/macros/utils/utils.sql
Reverts ClickHouse/dbt-clickhouse#245
> Revert "Bug/223 relationship test with limit"

- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/relation.py
- dbt/include/clickhouse/macros/adapters.sql
- dbt/include/clickhouse/macros/materializations/dictionary.sql
- dbt/include/clickhouse/macros/materializations/materialized_view.sql
- tests/integration/adapter/dictionary/test_dictionary.py
Adds a materialization macro to support materializing models as [dictionaries](https://clickhouse.com/docs/en/sql-reference/dictionaries). Tests are included for query-, table-, and HTTP-based dictionaries. These tests also include examples of how to configure models to be materialized as dictionaries.
> Add materialization macro for dictionaries

- dbt/adapters/clickhouse/dbclient.py
If using a custom materialization, an error occurs
```
File "/Users/silent/.pyenv/versions/dbt-pipelines/lib/python3.11/site-packages/dbt/adapters/clickhouse/impl.py", line 412, in get_model_settings
conn.handle.update_model_settings(settings, materialization_type)
File "/Users/silent/.pyenv/versions/dbt-pipelines/lib/python3.11/site-packages/dbt/adapters/clickhouse/dbclient.py", line 153, in update_model_settings
model_settings_to_add = copy.deepcopy(self._model_settings[materialization_type])
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'NAME_MAT'
```
> Fix model settings to use a custom materialization

- dbt/adapters/clickhouse/connections.py
- dbt/adapters/clickhouse/impl.py
TLDR: lazy-loading `agate` speeds up the load time of dbt by about 3.5%. Most instances of `agate` are unnecessary as dbt only uses it in a select few situations, and most instances of `agate` can be placed behind `TYPE_CHECKING`.
Already implemented in `dbt-adapters` and `dbt-core`.
- https://github.com/dbt-labs/dbt-adapters/pull/126
- https://github.com/dbt-labs/dbt-core/pull/9744
---
Note: usually I perform the following check with each adapter. The following code _should_ return an empty list:
```python
import sys
import dbt.adapters.clickhouse.impl
print([i for i in sys.modules if "agate" in i])
```
However, because `dbt-clickhouse` has not yet been migrated to the dbt-core `1.8` ecosystem, this check is not successful:
```python
>>> print([i for i in sys.modules if "agate" in i]) …
```
> lazy load `agate`

- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/dictionary.sql
This PR fixed an issue in which ClickHouse was using the configured host to load the dictionary, however, this would fail if it was running on Docker and would be slower if it was using a URL to connect to ClickHouse. It implements a new config for the dictionary model allowing people to override connection params.
`SOURCE(CLICKHOUSE(USER 'ch_admin' PASSWORD '[HIDDEN]' HOST 'clickhouse' PORT '8123' QUERY ...)`
`SOURCE(CLICKHOUSE(USER 'ch_admin' PASSWORD '[HIDDEN]' QUERY ...)`
> feat: allow to add connection overrides for dictionaries

- dbt/include/clickhouse/macros/utils/utils.sql
No issue created, but I can open one if needed.
This fixes an issue with the cross-database dbt macro `bool_or`. It was using `any` which selects the first non-null column value.  This means it can return false even if there is a true in the same group.  Updated the function to use the max function instead.
__Example:__
```sql
with my_test_values as (
select false as val
union all 
select true
union all
select null
)
select any(val), max(val)
from my_test_values
```
| any(val) | max(val) |
| -------- | --------- |
| false      | true         |
> Fix bool_or behavior

- dbt/adapters/clickhouse/impl.py
This PR addresses #88. Specifying a column codec requires contracts are enabled for the given model.
> feat: support column codecs

- dbt/include/clickhouse/macros/utils/utils.sql
- tests/integration/adapter/utils/test_listagg.py
Implement listagg macro, which is not supported at the moment
> feat: implement listagg macro

- README.md
- dbt/adapters/clickhouse/credentials.py
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/distributed_table.sql
- dbt/include/clickhouse/macros/materializations/incremental/distributed_incremental.sql
- dbt/include/clickhouse/macros/materializations/incremental/incremental.sql
Distributed Tables currently create their local tables within the same database. However, this is not always desirable as for other users of these tables it might not be clear which table to use. At the same time it is very different to apply seperate permissions to local tables. 
This PR creates the option to add a database prefix for local tables which allows for filtering and seperate permissions.
Closes #248 
> Added database prefix option for local tables of distributed tables

- CHANGELOG.md
- dbt/adapters/clickhouse/relation.py
- dbt/include/clickhouse/macros/materializations/dictionary.sql
Fixes an issue where dictionaries are not correctly run "ON CLUSTER" when a cluster is defined.
> Fix: Dictionaries should be created on cluster when cluster is set

- README.md
Fixed incorrect values in [Example Profile](https://github.com/ClickHouse/dbt-clickhouse?tab=readme-ov-file#example-profile) section in README.md file
- There were several lines where comment lines haven't been commented
- There were lines that didn't have a colon after keys
> Fixed incorrect values in <Example Profile> section in README.md

- README.md
Adds a new section in the README containing information about column-level configuration options.
- [ x] A human-readable description of the changes was provided to include in CHANGELOG
> Add documentation for codec column configuration

- dbt/include/clickhouse/macros/materializations/view.sql
Currently the `settings` configuration option is used when creating a view, but only at view **creation** time. These settings do not persist when actually querying the view, so this PR adds the option to use the separate `query_settings` config option to create a view with settings that persist at query time.
My specific use case is to allow `join_use_nulls=1` to be set within dbt, rather than remembering to include this setting every time I query the view.   
I'm a first timer here, so have a few questions too,
- There's no open issue yet - should I create one?
- I didn't see any tests that were relevant to this change, but if there are some that cover this just lemme know and I'll add some in :)
- Would also be great to know what specific docs would need to change if this is merged in?
> feat: support query_settings in view materialization

- dbt/include/clickhouse/macros/materializations/dictionary.sql
> __dbt_backup relation dropped on cluster for dictionaries (fixes #325)

- dbt/include/clickhouse/macros/materializations/seed.sql
Fixes #330: allow inserting an empty seed with column names only (in fact create table and do not insert anything)
> feat: allow adding an empty seed without rows

- CHANGELOG.md
- dbt/include/clickhouse/macros/materializations/distributed_table.sql
- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/projections/test_projections.py
close #319 
This PR introduces support for projections in `dbt-clickhouse`. Projections are added to the `table` and `distributed_table` materializations as a model setting. For distributed tables, the projection is applied to the `_local` tables, not to the distributed proxy table.
I added a test for each materialization. During test development, I encountered two challenges:
1. To verify that the projection was used by the query, we need to query `system.query_log`. However, this table takes time to create, which necessitates adding a sleep statement.
2. Currently, there's no straightforward way to pass a `query_id` parameter to ClickHouse, making it difficult to retrieve the exact query I want to check. As a workaround, I queried `system.query_log` using a `LIKE` statement.
> Support projections

- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/projections/test_projections.py
> Fix multiple projections issue

- README.md
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/s3.sql
Adding support for accessing S3 data with `extra_credentials`. 
For reference: https://clickhouse.com/docs/en/cloud/security/secure-s3.
> adding extra credentials argument to s3source

- dbt/include/clickhouse/macros/utils/utils.sql
- tests/integration/adapter/utils/test_split_part.py
It seems that there's extra quotes in split_part macro because if you run dbt_utils.get_url_paramter code for clickhouse results in extra quotes around field name.
Removed quotes around field_name.
> Fix quotation in split_part macro

- dbt/include/clickhouse/macros/materializations/dictionary.sql
The [range_hashed](https://clickhouse.com/docs/en/sql-reference/dictionaries#range_hashed) and [complex_key_range_hashed](https://clickhouse.com/docs/en/sql-reference/dictionaries#complex_key_range_hashed) dictionary layouts require a value is set for `RANGE` in the ddl. This PR checks the model config for the `range` key and sets one if provided by the materialization.
> feat: support range based dictionary layouts

- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/query_settings/test_query_settings.py
Fix for query_settings
Currently, when a table is created, the query settings are not passed to the query, which causes an issue with the join_use_nulls setting (empty table have not nullable column, and then we cant insert null into this column). This PR fixes this behavior.
> Apply query settings for empty table model

- CHANGELOG.md
- tests/integration/adapter/dictionary/test_dictionary.py
Following up on https://github.com/ClickHouse/dbt-clickhouse/pull/361#issuecomment-2446490479.
> Add range based dictionary to CHANGELOG + tests

- CHANGELOG.md
- dbt/adapters/clickhouse/httpclient.py
- dbt/adapters/clickhouse/nativeclient.py
- dbt/adapters/clickhouse/util.py
- tests/integration/adapter/dictionary/test_dictionary.py
- tests/unit/test_util.py
I'm always frustrated when scrolling throw stack trace to my actual errors in database.
#381 
**Solution**
Remove stack trace and keep only database errors.
**Before**
```
clickhouse adapter: ClickHouse server does not support exchange tables Database Error
Code: 1.
DB::Exception: System call renameat2() is not supported. Stack trace:
0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xce3f35a in /usr/bin/clickhouse
1. DB::renameExchange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x11a385a5 in /usr/bin/clickhouse
2. …
```
> Remove stacktrace from database errors

- CHANGELOG.md
- README.md
- dbt/include/clickhouse/macros/materializations/materialized_view.sql
- tests/integration/adapter/materialized_view/test_materialized_view.py
Proposed mechanism to support having multiple materialized views pointing to the same target table.
In brief, we add tags to mark blocks of the sql which will form each of the materialized views to be created. 
i.e. https://github.com/ClickHouse/dbt-clickhouse/pull/364/files#diff-b1cddf2e5c9b3d08ea2276e5cef4944b06b9744a4076c5970ff5a5edb0140f08R62.
The entire union of all such blocks is used to backfill the target table.
> Allow multiple materialized views to write to same target (#280)

- CHANGELOG.md
- dbt/include/clickhouse/macros/materializations/dictionary.sql
Dropping dictionary during model build can break anything that is currently running that depends on it. In particular materialized views that process high volumes of data, can miss processing data if they use a dictionary that is temporarily dropped.
- [ X] A human-readable description of the changes was provided to include in CHANGELOG
> Use `CREATE OR REPLACE DICTIONARY` to avoid data loss (#392)

- CHANGELOG.md
- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/basic/test_incremental.py
- tests/integration/adapter/clickhouse/test_clickhouse_s3.py
- tests/integration/adapter/incremental/test_base_incremental.py
- tests/integration/adapter/incremental/test_distributed_incremental.py
- tests/integration/adapter/incremental/test_schema_change.py
Enhance the `primary_key` macro to accept a list of columns, allowing for primary keys with multiple columns. This improves flexibility in configuration.
With this PR it's now possible to do the following:
```sql
{{
config(
primary_key=['a', 'b'],
order_by=['a', 'b'],
)
}}
-- ...
```
Before, you would need to use the literal expression as follows `primary_key='(a, b)'`
> Add list support to `primary_key`

- CHANGELOG.md
- dbt/include/clickhouse/macros/materializations/table.sql
- tests/integration/adapter/basic/test_incremental.py
- tests/integration/adapter/clickhouse/test_clickhouse_s3.py
- tests/integration/adapter/incremental/test_base_incremental.py
- tests/integration/adapter/incremental/test_distributed_incremental.py
- tests/integration/adapter/incremental/test_schema_change.py
Reverts ClickHouse/dbt-clickhouse#377
> Revert "Add list support to `primary_key`"

- dbt/include/clickhouse/macros/materializations/materialized_view.sql
If no rows are returned from the query then referencing element 0 fails.
https://github.com/ClickHouse/dbt-clickhouse/issues/395
> Protect against no columns returned in materialized-view (#395)

- setup.py
This pull request includes a change to the `setup.py` file to update the required Python version for the project.
Dependencies and requirements update:
* [`setup.py`](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L62-L70): Updated `python_requires` to require Python version 3.9 or higher and removed the classifier for Python 3.8.
> fix: remove python 3.8 from various places, #385

- CHANGELOG.md
- README.md
- dbt/include/clickhouse/macros/materializations/materialized_view.sql
- tests/integration/adapter/materialized_view/test_refreshable_materialized_view.py
Closes #252
This PR enhances the current mv implementation by introducing the ability to create refreshable materialized views.
Important Note: Currently, there is no direct "dbt linkage" between materialized views and their dependencies. As a result, the order of creation for dependencies is not guaranteed.
A potential solution to address this limitation is to pass a dbt ref object to the dependency list. However, this would require implementing MessagePack serialization to handle the references appropriately.
> Support refreshable materialized views

- README.md
- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/relation.py
- tests/integration/adapter/clickhouse/test_clickhouse_table_materializations.py
Closes https://github.com/ClickHouse/dbt-clickhouse/issues/327
This PR allows users to create relations on a cluster, regardless of their engine or materialization type.
> Add force on cluster config option

- CHANGELOG.md
- dbt/adapters/clickhouse/impl.py
- dbt/include/clickhouse/macros/materializations/distributed_table.sql
- dbt/include/clickhouse/macros/materializations/table.sql
- dbt/include/clickhouse/macros/materializations/view.sql
This PR introduces a feature that ignores settings that are not compatible with the Engine. More details in this issue: https://github.com/ClickHouse/dbt-clickhouse/issues/366
> Filter settings based on Engine

- CHANGELOG.md
- dbt/include/clickhouse/macros/materializations/materialized_view.sql
Dropping and recreating a materialized view risk losing some data. Instead we should use `ALTER TABLE...MODIFY QUERY` which performs the update atomically.
- [X ] A human-readable description of the changes was provided to include in CHANGELOG
> Prevent data loss when updating materialized view (#383)

- .github/workflows/test_matrix.yml
- CHANGELOG.md
- dbt/adapters/clickhouse/__version__.py
- dbt/include/clickhouse/macros/materializations/view.sql
- tests/integration/adapter/view/test_view.py
- tests/integration/docker-compose.yml
> Support replace view

- CHANGELOG.md
- README.md
- dbt/adapters/clickhouse/credentials.py
- dbt/adapters/clickhouse/httpclient.py
- dbt/adapters/clickhouse/nativeclient.py
Exposes the TLS client certificate settings from `clickhouse-connect`/`clickhouse-driver` as profile parameters.
> feat: allow using TLS client certificates

- CHANGELOG.md
- dbt/include/clickhouse/macros/materializations/incremental/distributed_incremental.sql
- dbt/include/clickhouse/macros/materializations/incremental/incremental.sql
- tests/integration/adapter/incremental/test_base_incremental.py
- tests/integration/adapter/incremental/test_distributed_incremental.py
Support of insert_overwrite in cluster setup with incremental and distributed_incremental materializations
1) In case is_distributed is True it creates distributed version of new data, gets partitions from cluster(system.parts) and replace in local existing table
2) The intermediate_relation entity was deleted as unnecessary because it is a incremental_legacy remnant. 
3) The existing test for insert_overwrite was renamed and made deterministic  
> Support of insert_overwrite in cluster setup

- CHANGELOG.md
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/relation.py
- dev_requirements.txt
- setup.py
- tests/integration/adapter/incremental/test_incremental_unique_key.py
Bump dbt-core version to 1.9.x. #380 
Requires dbt-adapters >= 1.10.0
> chore(deps): upgrade dbt-core to ~=1.9.0

- CHANGELOG.md
- Makefile
- README.md
- dbt/adapters/clickhouse/__version__.py
- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/relation.py
- dbt/include/clickhouse/macros/materializations/incremental/distributed_incremental.sql
- dbt/include/clickhouse/macros/materializations/incremental/incremental.sql
- dev_requirements.txt
- setup.py
- tests/integration/adapter/incremental/test_incremental_microbatch.py
Adds support for the incremental "microbatch" strategy #398, that comes with dbt-core 1.9.0 #403
Currently only works for non-distributed incremental model, as dbt-core has hard-coded [config.materialization = 'incremental'](https://github.com/dbt-labs/dbt-core/blob/0bf38ce294e21c6e4056ed36ba8f35538c10604a/core/dbt/task/run.py#L665) into a microbatching condition. Maybe this can be patched by the adapater though?
> feat: microbatch strategy

- dbt/include/clickhouse/macros/persist_docs.sql
Escape column names when generating column comments using persist_docs. https://github.com/ClickHouse/dbt-clickhouse/issues/427
> feat: escape column names in comments

- CHANGELOG.md
- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/relation.py
- dbt/include/clickhouse/macros/adapters.sql
- tests/integration/adapter/replicated_database/test_replicated_database.py
Previously, table and view materializations wouldn't work with a `Replicated` database configured, as they would run `ON CLUSTER` statements for some of the ddl's. This is not allowed in replicated databases and would lead to the following error:
```
DB::Exception: It's not initial query. ON CLUSTER is not allowed for Replicated database. (INCORRECT_QUERY) (version 24.11.1.2557 (official build)
```
This mr fixes these issues by adding conditions for on cluster statements with replicated databases.
> fix: replicated database materializations

- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/relation.py
- tests/integration/adapter/clickhouse/test_clickhouse_table_ttl.py
- tests/integration/adapter/replicated_database/test_replicated_database.py
When pushing #407, many tests were failing because of the `quoating` usage (quoting is only available for non-source nodes)
> fix quoting reference in database_engine usage

- CHANGELOG.md
- README.md
- dbt/adapters/clickhouse/impl.py
- dbt/adapters/clickhouse/relation.py
- dbt/include/clickhouse/macros/materializations/snapshot.sql
- tests/integration/adapter/clickhouse/test_clickhouse_table_materializations.py
- tests/integration/adapter/clickhouse/test_clickhouse_table_ttl.py
- tests/integration/adapter/incremental/test_base_incremental.py
- tests/integration/adapter/projections/test_projections.py
This PR refactors the logic around how the ON CLUSTER clause is applied during model creation in the dbt ClickHouse adapter. The motivation stems from ongoing confusion and inconsistency in how ON CLUSTER is handled, as documented in issues like #237, #225, #336, #327, #328, #384, and #307.
Close #417 
> Fix on cluster clause behaviour

- dbt/include/clickhouse/macros/materializations/table.sql
As reported in [this issue](https://github.com/ClickHouse/dbt-clickhouse/issues/456), when the last line of a model's SQL query is a comment (`-- some comment`) and the table's contract is enforced, the last parenthesis of the wrapping subquery ends up commented as well.
In order to solve the issue, I'm adding newlines around the wrapping parenthesis.
> Add newline around subquery parenthesis used when contract is enabled

- CHANGELOG.md
- dbt/adapters/clickhouse/impl.py
- tests/integration/adapter/query_settings/test_query_settings.py
Fixes #240: 
- When parsing query_settings, if the value is a string, quotes will get added.
- Also supports the workaround we suggested in https://github.com/ClickHouse/dbt-clickhouse/issues/240#issuecomment-1894692117 so this change would not break it. 
> Correctly parse query_settings when a String is added

- dbt/include/clickhouse/macros/adapters.sql
Fixes https://github.com/ClickHouse/dbt-clickhouse/issues/510
The new temp relation wasn't including the schema. That caused some queries like the one to `system.columns` to get incorrect values.
After fixing it I cannot find more situations where this is problematic.
This also should put us closer to the parallelisation of the cloud tests.
> Always include the schema when creating a temp relation

- .github/workflows/test_cloud_results.yml
This PR adds a placeholder workflow to test repository_dispatch triggers. The workflow currently does nothing; will be updated with actual logic in the follow-ups.
> ci: add `test_cloud_results.yml` placeholder workflow

- CHANGELOG.md
- dbt/include/clickhouse/macros/column_spec_ddl.sql
- tests/integration/adapter/constraints/fixtures_constraints.py
- tests/integration/adapter/constraints/test_constraints.py
This pull request resolves #303 by allowing the definition of columns as `LowCardinality` in the contracts. Before, defining a column of type `String` to be of type `LowCardinality(String)` caused an error if the constraints were enforced; otherwise, the `LowCardinality` was just ignored. 
Additionally, this PR allows defining special types that ignore the basic string comparison in the column constraints. 
At the moment, only the `SimpleAggregateFunction` is marked as a special type
> Fix: Improve LowCardinality validation for model contracts
