README.md
dbt/include/clickhouse/macros/materializations/test.sql
test/integration/clickhouse.dbtspec

Solve of this issue was suggested in dbt-labs/dbt#3872.
Same method used in MS SQL adapter.

Ability to run dbt tests with ClickHouse

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/pypi.yml
.yamllint
Makefile
dbt/adapters/clickhouse/__init__.py
dbt/adapters/clickhouse/impl.py
dbt/include/clickhouse/__init__.py
dbt/include/clickhouse/dbt_project.yml
dbt/include/clickhouse/sample_profiles.yml
dev_requirements.txt
tests/conftest.py
tests/docker-compose.yml
tests/integration/adapter/test_basic.py

The project is more public now, so we need automatic a style code and the code static checkers

Add python and yaml linters

---

README.md
dev_requirements.txt
setup.py
tests/conftest.py

Also fixes the docker test startup

Tweak driver versions

---

dbt/include/clickhouse/macros/materializations/incremental.sql

existing_table -> existing_relation

Fix incorrect variable name

---

dbt/include/clickhouse/macros/persist_docs.sql
tests/integration/adapter/test_comments.py

Add support persist docs

---

CHANGELOG.md
README.md
dbt/adapters/clickhouse/__version__.py
dbt/adapters/clickhouse/dbclient.py
dbt/adapters/clickhouse/httpclient.py
dev_requirements.txt
tests/integration/adapter/test_basic.py
tests/integration/adapter/test_singular.py
tests/integration/conftest.py

Add ephemeral tests, fix corruption of session_id

Release 1.3.3

---

dbt/include/clickhouse/macros/persist_docs.sql

Add the macro to modify comment for clusters.

Add `ON CLUSTER` to persist docs

---

dbt/include/clickhouse/macros/adapters.sql

Fix bug SYSTEM SYNC REPLICA
docs:
https://clickhouse.com/docs/en/sql-reference/statements/system#sync-replica

fix: SYSTEM SYNC REPLICA for on_cluster_clause

---

CHANGELOG.md
dbt/adapters/clickhouse/__version__.py
dbt/include/clickhouse/macros/materializations/incremental.sql

Fixes a bug in "legacy" incremental materializations introduced with distributed tables support

Fix legacy incremental materialization

---

dbt/include/clickhouse/macros/adapters.sql
dbt/include/clickhouse/macros/materializations/distributed_table.sql

The changes fixed the problem in the git issue https://github.com/ClickHouse/dbt-clickhouse/issues/179 .
The previous PR:  https://github.com/ClickHouse/dbt-clickhouse/pull/180

fix: distributed_table materialization issue

---

CHANGELOG.md
dbt/adapters/clickhouse/__version__.py

Bump version and changelog

---

dbt/adapters/clickhouse/dbclient.py

cluster names containing dash characters (#198)

---

CHANGELOG.md
dbt/adapters/clickhouse/__version__.py
dbt/adapters/clickhouse/dbclient.py

Add community Distributed Table materialization updates.

Update version and CHANGELOG, incorporate cluster name fix

---

.github/workflows/test_cloud.yml
.github/workflows/test_matrix.yml
CHANGELOG.md
dev_requirements.txt
setup.py

Clean up dependency/test versions

Update test and dependency versions.

---

dbt/adapters/clickhouse/dbclient.py
dbt/include/clickhouse/macros/materializations/view.sql

Thanks to the test `test_snapshot_check_cols.TestSnapshotCheckCols` I found out I didn't add all materializations when changing default settings in #250

Add snapshot materialization to default settings

---

CHANGELOG.md
README.md
dbt/adapters/clickhouse/__version__.py

Release 1.7.4 housekeeping

---

README.md
dbt/adapters/clickhouse/impl.py
dbt/include/clickhouse/macros/materializations/table.sql
tests/integration/adapter/clickhouse/test_clickhouse_table_ttl.py

feat: add TTL support

---

dbt/include/clickhouse/macros/materializations/distributed_table.sql

Related to https://github.com/ClickHouse/dbt-clickhouse/issues/226
It seems that after running the `EXCHANGE TABLES` command, the distributed table does not point to the local table anymore (see https://github.com/ClickHouse/dbt-clickhouse/issues/226).
While testing locally, I realized that if we run the `create_distributed_table` operation once more after the `EXCHANGE TABLES`, this fixes the problem. Even though I have very few context on dbt adapters, this hopefully helps figuring out the correct solution.

Update table relation after exchange command

---

CHANGELOG.md
dbt/adapters/clickhouse/__version__.py

Incorporate feature and bug fix PRs.

Housekeeping for 1.7.6 release

---

dbt/include/clickhouse/macros/materializations/table.sql
dbt/include/clickhouse/macros/materializations/view.sql

Reverts ClickHouse/dbt-clickhouse#228

Revert "allows to add a comment in table's or view's metadata"

---

dbt/include/clickhouse/macros/materializations/table.sql

fix: query_settings for models with contracts

---

dbt/include/clickhouse/macros/materializations/dictionary.sql

This PR fixes https://github.com/ClickHouse/dbt-clickhouse/issues/283.

Omit empty dictionary connection_overrides from materialization DDL

---

README.md
dbt/adapters/clickhouse/credentials.py
dbt/adapters/clickhouse/nativeclient.py

This PR closes https://github.com/ClickHouse/dbt-clickhouse/issues/233.

feat: Add tcp_keepalive for native connections

---

dbt/include/clickhouse/macros/utils/utils.sql
tests/integration/adapter/utils/test_listagg.py

Fixing `lisgagg` functionality and test (fixes https://github.com/ClickHouse/dbt-clickhouse/issues/301)

Fix listagg test

---

dbt/include/clickhouse/macros/materializations/table.sql

Fix temporary table creation to support dbt unit tests

---

dbt/include/clickhouse/macros/utils/utils.sql
tests/integration/adapter/utils/test_listagg.py

improve listagg macro and add more tests to cover (still need one to cover exception rase)

improve listagg macro 

---

.github/workflows/test_matrix.yml
tests/integration/conftest.py

Fix `docker-compose` command in our workflows. More details regarding the issue can be found at https://github.com/orgs/community/discussions/134407

Fix docker compose error in tests

---

CHANGELOG.md
dbt/adapters/clickhouse/__version__.py

Housekeeping for 1.8.4 release

---

dbt/include/clickhouse/macros/materializations/materialized_view.sql

Closes https://github.com/ClickHouse/dbt-clickhouse/issues/408

chore: allow optional whitespace in multi mv implementation

---

dbt/adapters/clickhouse/relation.py

create materialized view need ON CLUSTER keyword

fix: create materialized view on cluster

---

dbt/include/clickhouse/macros/materializations/distributed_table.sql
tests/integration/adapter/clickhouse/test_clickhouse_table_ttl.py

Add TTL materialization for distributed tables. Add corresponding tests. Fix #321.

Add TTL materialization for distributed tables.

---

dbt/adapters/clickhouse/relation.py

fix missing database_engine error

---

dbt/include/clickhouse/macros/materializations/snapshot.sql

add on cluster clause

---

CONTRIBUTING.md

Fix small issues in docs. Document DBT_CH_TEST_DRIVER
Related to https://github.com/ClickHouse/dbt-clickhouse/issues/484

Fix small issues in docs. Document DBT_CH_TEST_DRIVER
